### ISSUE TITLE
Cannot open source file: '..\..\sim\noble\execute.c?

### ISSUE THREAD

**Issue by anta40** [barbalet/apesdk#59]
Hi,

I just pulled the latest source code from Github, and the code failed to build with VS 2017.

> 1>c:\users\cipta-nb\desktop\nobleape-master\sim\noble\audio.c(249): warning C4244: '*=': conversion from 'n_double' to 'n_audio', possible loss of data
> 1>c:\users\cipta-nb\desktop\nobleape-master\sim\noble\audio.c(269): warning C4244: '=': conversion from 'n_uint' to 'n_byte', possible loss of data
> 1>compress.c
> 1>execute.c
> 1>c1 : fatal error C1083: Cannot open source file: '..\..\sim\noble\execute.c': No such file or directory
> 1>interpret.c
> 1>io.c

Seems like this execute.c is missing

**Comment by barbalet** [comment]
This should be fixed. When in doubt go to the gitlab.com/barbalet/apesdk repo with the active development.
